name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image-tag }}
    steps:
    - uses: actions/checkout@v4
    - name: Set lowercase repository owner and name
      id: set-variables
      run: |
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
        echo "repo-owner=$REPO_OWNER" >> $GITHUB_ENV
        echo "repo-name=$REPO_NAME" >> $GITHUB_ENV
        echo "::set-output name=repo-owner::$REPO_OWNER"
        echo "::set-output name=repo-name::$REPO_NAME"
        
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/$REPO_OWNER/$REPO_NAME:latest

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      
    - name: Push the Docker image
      run: docker push ${{ needs.build.outputs.image-tag }}

  scan:
    needs: push
    runs-on: ubuntu-latest
    steps:
    - name: Scan the Docker image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ needs.build.outputs.image-tag }}
